const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/adminController');
router.post('/login', ctrl.login);
router.get('/me', ctrl.me);
router.get('/dashboard', ctrl.dashboard);
router.get('/users', ctrl.getUsers);
router.put('/users/:userId', ctrl.updateUser);
router.get('/orders', ctrl.getOrders);
router.put('/orders/:orderId', ctrl.updateOrder);
router.get('/products/pending', ctrl.getPendingProducts);
router.put('/products/:productId', ctrl.approveProduct);
router.get('/transactions', ctrl.getTransactions);
router.put('/transactions/:txnId', ctrl.handleWithdrawal);
router.get('/reports/sales', ctrl.salesReport);
router.get('/reports/rider-performance', ctrl.riderPerformance);
router.put('/settings/general', ctrl.updateGeneralSettings);
router.put('/settings/commission', ctrl.updateCommission);
router.get('/tickets', ctrl.getTickets);
router.put('/tickets/:ticketId', ctrl.resolveTicket);
module.exports = router;
