const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const roleAuth = require('../middleware/roleAuth');
const ctrl = require('../controllers/orderController');
router.post('/', auth, roleAuth('customer'), ctrl.createOrder);
router.get('/', auth, ctrl.getOrders);
router.get('/:id', auth, ctrl.getOrder);
router.put('/:id/status', auth, roleAuth('rider','admin'), ctrl.updateOrderStatus);
module.exports = router;
