const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const roleAuth = require('../middleware/roleAuth');
const ctrl = require('../controllers/productController');
router.get('/', ctrl.getProducts);
router.get('/:id', ctrl.getProduct);
router.post('/', auth, roleAuth('wholesaler','admin'), ctrl.createProduct);
router.put('/:id', auth, roleAuth('wholesaler','admin'), ctrl.updateProduct);
module.exports = router;
