const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const roleAuth = require('../middleware/roleAuth');
const ctrl = require('../controllers/userController');
router.get('/', auth, roleAuth('admin'), ctrl.getUsers);
router.get('/:id', auth, ctrl.getUser);
router.put('/:id', auth, ctrl.updateUser);
router.delete('/:id', auth, roleAuth('admin'), ctrl.deleteUser);
module.exports = router;
